# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: 

home:
  style: default           # default, detail

favicon:                   # Path to the custom favicon (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true             # Display banner
  url: /assets/banner.webp
  position: center         # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true         # Display banner on all pages

# Appearence
hue: 270                   # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - recent_posts
      - category
      - tag
      - archive

# Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5

# Personal info
avatar: /assets/avatar.webp
author: NekoRectifier
subtitle: 人生中一半的麻烦源于答应的太快，拒绝的太慢。<hr>格雷格·麦基沃恩
links:
  - name: Twitter
    icon: fa-brands fa-twitter      # Find icon codes at https://fontawesome.com/search
    url: https://twitter.com/NekoRectifier
  - name: Telegram
    icon: fa-brands fa-telegram
    url: https://t.me/NekoRectifier
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/NekoRectifier

comment:
  valine:
    enable: false
    appId: 
    appKey: 
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs: 
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
